#!/usr/bin/env python3
"""
Auto-Tuning System - Runs automatically in background
======================================================
This module enables automatic game improvement without user intervention.

When enabled, the game will:
1. Analyze logs every N sessions (default: 10)
2. Auto-generate tuning adjustments
3. Apply them on next startup

Usage:
    # Add to main.py
    from auto_tune import check_and_apply_auto_tuning
    
    if __name__ == "__main__":
        # Auto-tune if enough data collected
        check_and_apply_auto_tuning()
        main()
"""

import json
from pathlib import Path
from typing import Any


def count_sessions() -> int:
    """Count total gameplay sessions logged."""
    log_dir = Path("logs")
    if not log_dir.exists():
        return 0
    
    # Count log files (exclude test logs)
    sessions = [f for f in log_dir.glob("game_*.jsonl") if "test" not in f.name]
    return len(sessions)


def get_sessions_since_last_tune() -> int:
    """Count sessions since last auto-tune ran."""
    config_file = Path("game_tuning.json")
    if not config_file.exists():
        # Never tuned - count all sessions
        return count_sessions()
    
    try:
        with open(config_file, "r", encoding="utf-8") as f:
            config = json.load(f)
            last_tune_count = config.get("metadata", {}).get("sessions_analyzed", 0)
            current_count = count_sessions()
            return current_count - last_tune_count
    except Exception:
        return count_sessions()


def should_auto_tune(min_sessions: int = 10) -> bool:
    """
    Check if we should run auto-tuning.
    
    Criteria:
    - At least min_sessions new sessions since last tune
    - OR no tuning config exists and we have min_sessions total
    """
    sessions_since_tune = get_sessions_since_last_tune()
    total_sessions = count_sessions()
    
    # Need at least min_sessions to tune
    if total_sessions < min_sessions:
        return False
    
    # Tune if enough new sessions
    return sessions_since_tune >= min_sessions


def run_auto_tuning(silent: bool = False) -> dict[str, Any]:
    """
    Run automatic tuning and return results.
    
    Args:
        silent: If True, suppress output
        
    Returns:
        dict with keys: success, adjustments, message
    """
    try:
        # Import game_tuner logic
        import game_tuner
        
        tuner = game_tuner.GameTuner(min_sessions=5)
        sessions = tuner.load_all_sessions()
        
        if len(sessions) < 5:
            return {
                "success": False,
                "adjustments": {},
                "message": f"Need 5+ sessions for tuning (have {len(sessions)})"
            }
        
        # Run analysis
        tuner.analyze_theme_balance(sessions)
        tuner.analyze_death_causes(sessions)
        tuner.analyze_difficulty_scaling(sessions)
        tuner.analyze_event_frequency(sessions)
        tuner.analyze_progression_pacing(sessions)
        
        if not tuner.adjustments:
            return {
                "success": True,
                "adjustments": {},
                "message": "Game is balanced - no adjustments needed! 🎮"
            }
        
        # Generate config
        config = {
            "version": "1.0",
            "generated": "auto-tuning",
            "note": "Auto-generated by background tuning system",
            "adjustments": tuner.adjustments,
            "metadata": {
                "sessions_analyzed": len(sessions),
                "insights": tuner.insights
            }
        }
        
        # Save
        with open("game_tuning.json", "w", encoding="utf-8") as f:
            json.dump(config, f, indent=2)
        
        if not silent:
            print(f"\n🎯 Auto-tuning applied! ({len(tuner.adjustments)} adjustments)")
            for insight in tuner.insights[:3]:  # Show top 3
                print(f"  • {insight}")
        
        return {
            "success": True,
            "adjustments": tuner.adjustments,
            "message": f"Applied {len(tuner.adjustments)} adjustments"
        }
        
    except Exception as e:
        return {
            "success": False,
            "adjustments": {},
            "message": f"Auto-tuning failed: {e}"
        }


def check_and_apply_auto_tuning(min_sessions: int = 10, silent: bool = False) -> bool:
    """
    Check if auto-tuning should run and apply it if needed.
    
    This is the main entry point - call this at game startup.
    
    Args:
        min_sessions: Minimum sessions before tuning (default: 10)
        silent: If True, don't show output
        
    Returns:
        True if tuning was applied, False otherwise
    """
    if not should_auto_tune(min_sessions):
        return False
    
    if not silent:
        sessions = get_sessions_since_last_tune()
        print(f"\n🔧 Auto-tuning: {sessions} new sessions detected...")
        print("   Analyzing gameplay patterns and applying fixes...")
    
    result = run_auto_tuning(silent=silent)
    
    if result["success"] and result["adjustments"]:
        if not silent:
            print(f"   ✅ {result['message']}")
            print("   Changes will apply to your next game!\n")
        return True
    
    return False


if __name__ == "__main__":
    # For testing
    print("Auto-Tuning System Status")
    print("=" * 50)
    print(f"Total sessions: {count_sessions()}")
    print(f"Sessions since last tune: {get_sessions_since_last_tune()}")
    print(f"Should auto-tune?: {should_auto_tune()}")
    
    if should_auto_tune():
        print("\nRunning auto-tune...")
        result = run_auto_tuning()
        print(f"Result: {result['message']}")
